["pyproject.toml".tool.pdm.dev-dependencies]
checkstyle = [
    "flake8>=7.2.0",
    "flake518>=1.6.0",
    "flake8-type-checking>=3.0.0",
]

["pyproject.toml".tool.pdm.scripts]
flake = "flake518 src/"
