["pyproject.toml".tool.pdm.dev-dependencies]
checkstyle = [
    "pysonar>=1.0"
]

["pyproject.toml".tool.sonar.log]
level = "INFO"

["pyproject.toml".tool.sonar.python.coverage]
reportPaths = "dist/results/qa/pytest.coverage*.xml"

["pyproject.toml".tool.sonar.python.xunit]
reportpath = "dist/results/qa/pytest.result.*xml"
skipDetails = true

["pyproject.toml".tool.sonar.python.pylint]
reportPaths = "dist/results/metrics/pylint/**/*.*"

["pyproject.toml".tool.sonar.python.bandit]
reportPaths = "dist/results/metrics/bandit/**/*.*"

["pyproject.toml".tool.sonar.python.flake8]
reportPaths = "dist/results/metrics/flake8/**/*.*"

["pyproject.toml".tool.sonar.python.mypy]
reportPaths = "dist/results/metrics/mypy/**/*.*"

["pyproject.toml".tool.sonar.python.ruff]
reportPaths = "dist/results/metrics/ruff/**/*.*"

["pyproject.toml".tool.sonar.scm.exclusions]
disabled = false

["pyproject.toml".tool.sonar.link]
