["pyproject.toml".tool.pdm.dev-dependencies]
release = [
    "gitlint>=0.19.1",
]

[".gitlint".general]
ignore-merge-commits=true
ignore-revert-commits=true
fail-without-commits=true
contrib=CT1

[".gitlint".title-max-length]
line-length=50

[".gitlint".title-min-length]
min-length=5

[".gitlint".body-max-line-length]
line-length=72

[".gitlint".body-min-length]
min-length=5

[".gitlint".body-is-missing]
ignore-merge-commits=true

[".gitlint".contrib-title-conventional-commits]
types = feat,fix,docs,chore,build,ci,qa,style,refactor,perf,test
