[".renovaterc.json"]
extends=["config:recommended"]
addLabels=["dependencies","renovatebot"]
assignees=["carstencodes"]
assigneesFromCodeOwners=true
automerge=true
automergeStrategy="rebase"
automergeType="branch"
branchPrefix="renovate/"
commitBodyTable=true
commitMessagePrefix="chore(deps): "
commitMessageSuffix="Automatically created by mend renovate bot."
draftPR=false
enabled=true
enabledManagers=["pep621","pyenv","github-actions"]
osvVulnerabilityAlerts=true
packageRules=[
    {
        matchManagers=["pep621"],
        rangeStrategy="bump"
    },
    {
        matchManagers=["pyenv"],
        rangeStratege="replace"
    },
    {
        matchManagers=["github-actions"],
        rangeStrategy="replace"
    }
]
platformAutomerge=true
pruneBranchAfterAutomerge=true
pruneStaleBranches=true
rebaseWhen="behind-base-branch"
timezone="Etc/UTC"
updateLockFiles=true
updateNotScheduled=true
